/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package lab1_keyboard;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;

/**
 *
 * @author user
 */
public class keyboardButtons{
    public static int buttonsCodeArr[] ={
        KeyEvent.VK_BACK_QUOTE,
        KeyEvent.VK_1,
        KeyEvent.VK_2,
        KeyEvent.VK_3,
        KeyEvent.VK_4,
        KeyEvent.VK_5,
        KeyEvent.VK_6,
        KeyEvent.VK_7,
        KeyEvent.VK_8,
        KeyEvent.VK_9,
        KeyEvent.VK_0,
        KeyEvent.VK_MINUS,
        KeyEvent.VK_EQUALS,
        KeyEvent.VK_BACK_SPACE,
        KeyEvent.VK_TAB,
        KeyEvent.VK_Q,
        KeyEvent.VK_W,
        KeyEvent.VK_E,
        KeyEvent.VK_R,
        KeyEvent.VK_T,
        KeyEvent.VK_Y,
        KeyEvent.VK_U,
        KeyEvent.VK_I,
        KeyEvent.VK_O,
        KeyEvent.VK_P,
        KeyEvent.VK_OPEN_BRACKET,
        KeyEvent.VK_CLOSE_BRACKET,
        KeyEvent.VK_ENTER,
        KeyEvent.VK_CAPS_LOCK,
        KeyEvent.VK_A,
        KeyEvent.VK_S,
        KeyEvent.VK_D,
        KeyEvent.VK_F,
        KeyEvent.VK_G,
        KeyEvent.VK_H,
        KeyEvent.VK_J,
        KeyEvent.VK_K,
        KeyEvent.VK_L,
        KeyEvent.VK_SEMICOLON,
        KeyEvent.VK_QUOTE,
        KeyEvent.VK_BACK_SLASH,
        KeyEvent.VK_SHIFT,
        KeyEvent.VK_Z,
        KeyEvent.VK_X,
        KeyEvent.VK_C,
        KeyEvent.VK_V,
        KeyEvent.VK_B,
        KeyEvent.VK_N,
        KeyEvent.VK_M,
        KeyEvent.VK_COMMA,
        KeyEvent.VK_PERIOD,
        KeyEvent.VK_SLASH,
        KeyEvent.VK_SHIFT,
        KeyEvent.VK_UP,
        KeyEvent.VK_CONTROL,
        KeyEvent.VK_WINDOWS,
        KeyEvent.VK_ALT,
        KeyEvent.VK_SPACE,
        KeyEvent.VK_ALT,
        KeyEvent.VK_WINDOWS,
        KeyEvent.VK_CONTEXT_MENU,
        KeyEvent.VK_CONTROL,
        KeyEvent.VK_LEFT,
        KeyEvent.VK_DOWN,
        KeyEvent.VK_RIGHT,
    };
    public static String buttonsNamesArr[] ={
        "`",
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "0",
        "-",
        "=",
        "       ",
        "Tab ",
        "Q",
        "W",
        "E",
        "R",
        "T",
        "Y",
        "U",
        "I",
        "O",
        "P",
        "[",
        "]",
        "ENTER",
        "Caps Lock  ",
        "A",
        "S",
        "D",
        "F",
        "G",
        "H",
        "J",
        "K",
        "L",
        ";",
        "'",
        "\\",
        " Shift    ",
        "Z",
        "X",
        "C",
        "V",
        "B",
        "N",
        "M",
        ",",
        ".",
        "/",
        " Shift    ",
        "",
        "Ctrl",
        "",
        "Alt",
        "                    Space                    ",
        "Alt",
        "",
        "",
        "Ctrl",
        "",
        "",
        "",
    };
}
